spring:
  mvc:
    pathmatch:
      # https://doc.xiaominfo.com/docs/quick-start
      # 如果开发者使用的是Knife4j 2.x版本，并且Spring Boot版本高于2.4,那么需要在Spring Boot的yml文件中做如下配置：
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:1103/xiaozhao?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
tencent:
  domainName: iai.tencentcloudapi.com
  region: ap-guangzhou
qiniu:
  bucket: trade-server
  region: huadongzhejiang2
  domain: www.lyggwsp.work
  accelerateUploadDomain: upload-cn-east-2.qiniup.com